name: Dreamworld
main: de.blablubbabc.dreamworld.DreamworldPlugin
version: 1.2
author: blablubbabc
description: Dreamworld by blablubbabc.
softdepend: [Multiverse-Core, My Worlds, Transporter]
commands:
    dreamworld:
      description: Dreamworld commands.
      usage: /<command> help
      aliases: dw
permissions:
  dreamworld.dream:
    description: Ability to dream.
    default: true
  dreamworld.admin:
    description: Access to the admin commands.
    default: op